### ISSUE TITLE
Pickle Insta 화면 <> 버튼 클릭시 IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Charlezz** [sabujak-sabujak/Pickle#11]
2019-12-06 11:19:34.819 19240-19240/life.sabujak.picklesample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: life.sabujak.picklesample, PID: 19240
    java.lang.IndexOutOfBoundsException: Index: -1, Size: 180188
        at androidx.paging.PagedList.loadAround(PagedList.java:424)
        at androidx.paging.AsyncPagedListDiffer.getItem(AsyncPagedListDiffer.java:216)
        at androidx.paging.PagedListAdapter.getItem(PagedListAdapter.java:176)
        at life.sabujak.pickle.ui.insta.InstaAdapter.getPickleMeida(InstaAdapter.kt:70)
        at life.sabujak.pickle.ui.insta.InstaFragment.loadImageView(InstaFragment.kt:87)
        at life.sabujak.pickle.ui.insta.InstaFragment$onCreate$2.onChanged(InstaFragment.kt:59)
        at life.sabujak.pickle.ui.insta.InstaFragment$onCreate$2.onChanged(InstaFragment.kt:24)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at life.sabujak.pickle.ui.insta.PreViewModel.ratioClicked(PreViewModel.kt:19)
        at life.sabujak.pickle.databinding.FragmentInstaBindingImpl._internalCallbackOnClick(FragmentInstaBindingImpl.java:126)
        at life.sabujak.pickle.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:7333)
        at android.view.View.performClickInternal(View.java:7299)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27773)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by Charlezz** [comment]
아무 이미지도 선택 안했을 때 클릭하면 크래시가 발생합니다.
